name: eticket
description: Application for purchase e-ticket

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.5+8

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  intl: any

  easy_localization: ^3.0.3
  get_it: ^7.6.0
  auto_route: ^7.8.3

  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.1
  dartz: ^0.10.1

  freezed_annotation: 2.4.1

  dio: ^5.3.3

  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0

  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  uuid: ^4.2.1

  permission_handler: ^10.4.3
  path_provider: 2.1.1

  image_picker: ^1.0.4
  image_cropper: ^5.0.0

  tuple: ^2.0.2
  mask_text_input_formatter: ^2.5.0
  dropdown_button2: ^2.3.4

  lottie: ^2.7.0

  flutter_native_splash: ^2.3.1

  qr_flutter: ^4.1.0

  dots_indicator: ^3.0.0

  sembast: ^3.5.0+1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  mobile_scanner: ^3.5.2
  zoom_widget: ^2.0.1
  url_launcher: ^6.2.6
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.18
  firebase_analytics: ^10.8.9

  package_info_plus: 4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner:

  flutter_launcher_icons: ^0.13.1

  freezed: ^2.4.5
  json_serializable: ^6.7.0

  auto_route_generator: ^7.2.0

  flutter_gen_runner:

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/payments/
    - assets/svgs/
    - assets/svgs/booking/
    - assets/logos/
    - assets/translations/
    - assets/lotties/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    lottie: true
